import { randomUUID } from "node:crypto";
import { CommercialLeadLogAction, CommercialPilotDecision, CommercialPilotStatus } from "@prisma/client";
import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { requireEloGestSuperAdmin } from "@/lib/elogest-api-guard";
import { DEFAULT_PILOT_ITEMS } from "@/lib/commercial-pilot";
export const dynamic = "force-dynamic";
type Ctx = { params: Promise<{ id: string }> };
const text=(v:unknown)=>typeof v==="string"&&v.trim()?v.trim():null;
const date=(v:unknown)=>typeof v==="string"&&v?new Date(v):null;
const arr=(v:unknown)=>Array.isArray(v)?v.filter((x):x is string=>typeof x==="string"&&!!x.trim()).map(x=>x.trim()):[];
export async function GET(_r:NextRequest,{params}:Ctx){const auth=await requireEloGestSuperAdmin();if("error" in auth)return auth.error;const{id}=await params;const pilot=await db.commercialPilot.findUnique({where:{commercialLeadProfileId:id},include:{items:{orderBy:{position:"asc"}},evidences:{orderBy:{createdAt:"desc"}}}});return NextResponse.json({pilot});}
export async function POST(request:NextRequest,{params}:Ctx){const auth=await requireEloGestSuperAdmin();if("error" in auth)return auth.error;const{id}=await params;const body=await request.json() as Record<string,unknown>;const lead=await db.commercialLeadProfile.findUnique({where:{id},select:{id:true}});if(!lead)return NextResponse.json({error:"Lead comercial não encontrado."},{status:404});const title=text(body.title);if(!title)return NextResponse.json({error:"Informe o título do piloto."},{status:400});const existing=await db.commercialPilot.findUnique({where:{commercialLeadProfileId:id},select:{id:true}});if(existing)return NextResponse.json({error:"Este lead já possui um piloto comercial."},{status:409});const status=Object.values(CommercialPilotStatus).includes(body.status as CommercialPilotStatus)?body.status as CommercialPilotStatus:CommercialPilotStatus.DRAFT;const pilot=await db.$transaction(async tx=>{const created=await tx.commercialPilot.create({data:{id:randomUUID(),commercialLeadProfileId:id,title,condominiumOrOperation:text(body.condominiumOrOperation),objective:text(body.objective),modules:arr(body.modules),internalResponsible:text(body.internalResponsible),clientResponsible:text(body.clientResponsible),startDate:date(body.startDate),expectedEndDate:date(body.expectedEndDate),status,createdByUserId:auth.authUser.id,items:{create:DEFAULT_PILOT_ITEMS.map((item,position)=>({id:randomUUID(),title:item,position}))}} ,include:{items:{orderBy:{position:"asc"}},evidences:true}});await tx.commercialLeadLog.create({data:{commercialLeadProfileId:id,action:CommercialLeadLogAction.NOTE_ADDED,description:`Piloto comercial criado: ${title}.`,metadata:{pilotId:created.id,status:created.status},createdByUserId:auth.authUser.id}});return created;});return NextResponse.json({pilot},{status:201});}
export async function PATCH(request:NextRequest,{params}:Ctx){const auth=await requireEloGestSuperAdmin();if("error" in auth)return auth.error;const{id}=await params;const body=await request.json() as Record<string,unknown>;const current=await db.commercialPilot.findUnique({where:{commercialLeadProfileId:id}});if(!current)return NextResponse.json({error:"Piloto não encontrado."},{status:404});const status=Object.values(CommercialPilotStatus).includes(body.status as CommercialPilotStatus)?body.status as CommercialPilotStatus:current.status;const decision=Object.values(CommercialPilotDecision).includes(body.decision as CommercialPilotDecision)?body.decision as CommercialPilotDecision:current.decision;const updated=await db.$transaction(async tx=>{const pilot=await tx.commercialPilot.update({where:{id:current.id},data:{title:text(body.title)??current.title,condominiumOrOperation:text(body.condominiumOrOperation),objective:text(body.objective),modules:arr(body.modules),internalResponsible:text(body.internalResponsible),clientResponsible:text(body.clientResponsible),startDate:date(body.startDate),expectedEndDate:date(body.expectedEndDate),actualEndDate:date(body.actualEndDate),status,decision,finalEvaluation:text(body.finalEvaluation),decisionNotes:text(body.decisionNotes),updatedByUserId:auth.authUser.id},include:{items:{orderBy:{position:"asc"}},evidences:{orderBy:{createdAt:"desc"}}}});await tx.commercialLeadLog.create({data:{commercialLeadProfileId:id,action:CommercialLeadLogAction.NOTE_ADDED,description:`Piloto comercial atualizado: ${pilot.title}.`,metadata:{pilotId:pilot.id,status:pilot.status,decision:pilot.decision},createdByUserId:auth.authUser.id}});return pilot;});return NextResponse.json({pilot:updated});}
